import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import MainCard from 'components/MainCard';

export default function NoSnapshotState() {
  return (
    <MainCard>
      <Stack spacing={1.5} alignItems="center" sx={{ py: 5, px: 2 }}>
        <Typography variant="h4">No Snapshot Available Yet</Typography>
        <Typography variant="body2" color="text.secondary">
          Forecast snapshot has not been generated by admin for this quarter.
        </Typography>
      </Stack>
    </MainCard>
  );
}
